.TH DISKO 1 2023\-03\-09 "disko 0.1.0" "disko manual"

.nh
.ad l

.SH NAME
disko \- display info about a disk's MBR and GPT

.SH SYNOPSIS
\fBdisko \fR[\fIOPTION\fR]... \fIDISK

.SH DESCRIPTION
The disko utility,
given a disk or disk image,
will display the requested information depending on options passed.

.SH OPTIONS
Currently only two options are supported:

.TP
.B \-h
Displays usage and help info.

.TP
.B \-v
Displays the name and version of disko.

.SH SEE ALSO
.BR fdisk (8)
